<!DOCTYPE html>
<html lang="de">
<head>
    <?php include ROOT_PATH."/app/views/forms/head.phtml";?>
</head>
<body data-background-color="dark">
<div class="wrapper">
    <?php include ROOT_PATH."/app/views/forms/mainheader.phtml";?>

    <!-- Sidebar -->
    <?php include ROOT_PATH."/app/views/forms/sidebar.phtml";?>
    <!-- End Sidebar -->

    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <h4 class="page-title">Statistiken zu Nachrichten</h4>
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="http://localhost/verany/tcp/dark/">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Administration</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Statistiken zu Nachrichten</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <button class="btn btn-primary" onclick="window.location.href='http://localhost/verany/tcp/dark/admin/messages.php'">Zurück zu den Übersetzungen</button>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><b>Englische</b></h5>
                                        <p class="text-muted">Übersetzungen</p>
                                    </div>
                                    <h3 class="text-info fw-bold">2.310</h3>
                                </div>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-info w-75" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between mt-2">
                                    <p class="text-muted mb-0"></p>
                                    <p class="text-muted mb-0">98%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><b>Deutsche</b></h5>
                                        <p class="text-muted">Übersetzungen</p>
                                    </div>
                                    <h3 class="text-info fw-bold">2.310</h3>
                                </div>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-info w-75" role="progressbar" aria-valuenow="76" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between mt-2">
                                    <p class="text-muted mb-0"></p>
                                    <p class="text-muted mb-0">76%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><b>Französische</b></h5>
                                        <p class="text-muted">Übersetzungen</p>
                                    </div>
                                    <h3 class="text-info fw-bold">2.310</h3>
                                </div>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-info w-75" role="progressbar" aria-valuenow="8" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between mt-2">
                                    <p class="text-muted mb-0"></p>
                                    <p class="text-muted mb-0">12%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><b>Spanische</b></h5>
                                        <p class="text-muted">Übersetzungen</p>
                                    </div>
                                    <h3 class="text-info fw-bold">2.310</h3>
                                </div>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-info w-75" role="progressbar" aria-valuenow="14" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between mt-2">
                                    <p class="text-muted mb-0"></p>
                                    <p class="text-muted mb-0">5%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><b>Niederländische</b></h5>
                                        <p class="text-muted">Übersetzungen</p>
                                    </div>
                                    <h3 class="text-info fw-bold">2.310</h3>
                                </div>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-info w-75" role="progressbar" aria-valuenow="14" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between mt-2">
                                    <p class="text-muted mb-0"></p>
                                    <p class="text-muted mb-0">1%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><b>Russische</b></h5>
                                        <p class="text-muted">Übersetzungen</p>
                                    </div>
                                    <h3 class="text-info fw-bold">2.310</h3>
                                </div>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-info w-75" role="progressbar" aria-valuenow="14" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between mt-2">
                                    <p class="text-muted mb-0"></p>
                                    <p class="text-muted mb-0">1%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6">
                        <div class="col-6 col-md-5">
                            <div class="nav flex-column nav-pills nav-primary nav-pills-no-bd nav-pills-icons" id="v-pills-tab-with-icon" role="tablist" aria-orientation="vertical">
                                <a class="nav-link active show" id="v-pills-home-tab-icons" data-toggle="pill" href="#v-pills-home-icons" role="tab" aria-controls="v-pills-home-icons" aria-selected="true">
                                    <i class="fas fa-plus"></i>
                                    Übersetzung hinzufügen
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include ROOT_PATH."/app/views/forms/footer.phtml";?>
    </div>

</div>
<?php include ROOT_PATH."/app/views/forms/scripts.phtml";?>
</body>
</html>
