<!DOCTYPE html>
<html lang="de">
<head>
    <?php include ROOT_PATH."/app/views/forms/head.phtml";?>
</head>
<body data-background-color="dark">
<div class="wrapper">
    <?php include ROOT_PATH."/app/views/forms/mainheader.phtml";?>

    <!-- Sidebar -->
    <?php include ROOT_PATH."/app/views/forms/sidebar.phtml";?>
    <!-- End Sidebar -->

    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <h4 class="page-title">Terminal</h4>
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="http://localhost/verany/tcp/dark/">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Administration</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Terminal</a>
                        </li>
                    </ul>
                </div>
                <div class="page-category">Diese Seite befindet sich derzeit in Wartungsarbeiten.</div>
            </div>
        </div>
        <?php include ROOT_PATH."/app/views/forms/footer.phtml";?>
    </div>

</div>
<?php include ROOT_PATH."/app/views/forms/scripts.phtml";?>
</body>
</html>
