<!DOCTYPE html>
<html lang="de">
<head>
    <?php include ROOT_PATH."/app/views/forms/head.phtml";?>
</head>
<body data-background-color="dark">
<div class="wrapper">
    <?php include ROOT_PATH."/app/views/forms/mainheader.phtml";?>

    <!-- Sidebar -->
    <?php include ROOT_PATH."/app/views/forms/sidebar.phtml";?>
    <!-- End Sidebar -->

    <div class="main-panel">
        <div class="content">
            <div class="panel-header bg-primary-gradient">
                <div class="page-inner py-5">
                    <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                        <div>
                            <h2 class="text-white pb-2 fw-bold">Marketing Dashboard</h2>
                            <h5 class="text-white op-7 mb-2">Internes Panel für das Verany Marketing Team.</h5>
                        </div>
                        <div class="ml-md-auto py-2 py-md-0">
                            <a href="#" class="btn btn-info btn-round">Neuer Partner</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-inner mt--5">
                <div class="row row-card-no-pd mt--2">
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-twitter text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Follower</p>
                                            <h4 class="card-title">186</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-youtube text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Abonnenten</p>
                                            <h4 class="card-title">170</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-twitch text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Follower</p>
                                            <h4 class="card-title">12</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-instagram text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Follower</p>
                                            <h4 class="card-title">5</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-discord text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Nutzer</p>
                                            <h4 class="card-title">297</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-github text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Follower</p>
                                            <h4 class="card-title">5</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-teamspeak text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Registrierte Nutzer</p>
                                            <h4 class="card-title">5</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-stats card-round">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <div class="icon-big text-center">
                                            <i class="fab fa-telegram text-primary"></i>
                                        </div>
                                    </div>
                                    <div class="col-7 col-stats">
                                        <div class="numbers">
                                            <p class="card-category">Kontakte</p>
                                            <h4 class="card-title">5</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-head-row">
                                    <div class="card-title">Spieler Statistiken</div>
                                    <div class="card-tools">
                                        <a href="#" class="btn btn-info btn-border btn-round btn-sm mr-2">
													<span class="btn-label">
														<i class="fa fa-share"></i>
													</span>
                                            Teilen
                                        </a>
                                        <a href="#" class="btn btn-info btn-border btn-round btn-sm mr-2">
													<span class="btn-label">
														<i class="fa fa-download"></i>
													</span>
                                            Herunterladen
                                        </a>
                                        <a href="#" class="btn btn-info btn-border btn-round btn-sm">
													<span class="btn-label">
														<i class="fa fa-print"></i>
													</span>
                                            Drucken
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="chart-container" style="min-height: 375px">
                                    <canvas id="statisticsChart"></canvas>
                                </div>
                                <div id="myChartLegend"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-primary">
                            <div class="card-header">
                                <div class="card-title">Einnahmen in diesem Quartal</div>
                                <div class="card-category">1. Juli 2020 - 30. September 2020</div>
                            </div>
                            <div class="card-body pb-0">
                                <div class="mb-4 mt-2">
                                    <h1>€ 00,00</h1>
                                </div>
                                <div class="pull-in">
                                    <canvas id="dailySalesChart"></canvas>
                                </div>
                            </div>
                        </div>
                        <div class="card card-primary bg-primary-gradient">
                            <div class="card-body">
                                <h4 class="mb-1 fw-bold">Task Fortschritt</h4>
                                <div id="task-complete" class="chart-circle mt-4 mb-3"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body pb-0">
                                <div class="h1 fw-bold float-right text-warning">+0%</div>
                                <h2 class="mb-2">2</h2>
                                <p class="text-muted">Spieler online</p>
                                <div class="pull-in sparkline-fix">
                                    <div id="lineChart"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body pb-0">
                                <div class="h1 fw-bold float-right text-success">+3%</div>
                                <h2 class="mb-2">27</h2>
                                <p class="text-muted">Neue Spieler (in diesem Quartal)</p>
                                <div class="pull-in sparkline-fix">
                                    <div id="lineChart2"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body pb-0">
                                <div class="h1 fw-bold float-right text-warning">+0%</div>
                                <h2 class="mb-2">0</h2>
                                <p class="text-muted">Käufe</p>
                                <div class="pull-in sparkline-fix">
                                    <div id="lineChart3"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-card-no-pd">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-head-row">
                                    <h4 class="card-title">Spieler Herkunft</h4>
                                    <div class="card-tools">
                                        <button class="btn btn-icon btn-link btn-primary btn-xs btn-refresh-card"><span class="fa fa-sync-alt"></span></button>
                                    </div>
                                </div>
                                <p class="card-category">
                                    Map der Herkunft der Spieler</p>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="table-responsive table-hover table-sales">
                                            <table class="table">
                                                <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="flag">
                                                            <img src="../../assets/img/flags/de.png" alt="indonesia">
                                                        </div>
                                                    </td>
                                                    <td>Deutschland</td>
                                                    <td class="text-right">
                                                        268
                                                    </td>
                                                    <td class="text-right">
                                                        36,9%
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="flag">
                                                            <img src="../../assets/img/flags/us.png" alt="united states">
                                                        </div>
                                                    </td>
                                                    <td>USA</td>
                                                    <td class="text-right">
                                                        103
                                                    </td>
                                                    <td class="text-right">
                                                        14,2%
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="flag">
                                                            <img src="../../assets/img/flags/at.png" alt="australia">
                                                        </div>
                                                    </td>
                                                    <td>Österreich</td>
                                                    <td class="text-right">
                                                        61
                                                    </td>
                                                    <td class="text-right">
                                                        8,4%
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="flag">
                                                            <img src="../../assets/img/flags/ch.png" alt="russia">
                                                        </div>
                                                    </td>
                                                    <td>Schweiz</td>
                                                    <td class="text-right">
                                                        47
                                                    </td>
                                                    <td class="text-right">
                                                        6,5%
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="flag">
                                                            <img src="../../assets/img/flags/fr.png" alt="china">
                                                        </div>
                                                    </td>
                                                    <td>Frankreich</td>
                                                    <td class="text-right">
                                                        34
                                                    </td>
                                                    <td class="text-right">
                                                        4,7%
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mapcontainer">
                                            <div id="map-example" class="vmap"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include ROOT_PATH."/app/views/forms/footer.phtml";?>
    </div>

</div>
<?php include ROOT_PATH."/app/views/forms/scripts.phtml";?>
<script>

</script>
</body>
</html>
