<!DOCTYPE html>
<html lang="de">
<head>
    <?php include ROOT_PATH."/app/views/forms/head.phtml";?>
</head>
<body data-background-color="dark">
<div class="wrapper">
    <?php include ROOT_PATH."/app/views/forms/mainheader.phtml";?>

    <!-- Sidebar -->
    <?php include ROOT_PATH."/app/views/forms/sidebar.phtml";?>
    <!-- End Sidebar -->

    <div class="main-panel">
        <div class="content">
        </div>
        <?php include ROOT_PATH."/app/views/forms/footer.phtml";?>
    </div>
</div>
<?php include ROOT_PATH."/app/views/forms/scripts.phtml";?>
<script>
    var SweetAlert2Demo = function() {

        var initDemos = function() {

            $(document).delegate('#deleteAlert', 'click', function(e){
                swal({
                    title: 'Sicher?',
                    text: "Die Datei wird endgültig gelöscht!",
                    type: 'warning',
                    buttons:{
                        cancel: {
                            visible: true,
                            text : 'Nein, abbrechen!',
                            className: 'btn btn-danger'
                        },
                        confirm: {
                            text : 'Ja, löschen!',
                            className : 'btn btn-success'
                        }
                    }
                }).then((willDelete) => {
                    if (willDelete) {
                        swal("Erfolgreich gelöscht!", {
                            icon: "success",
                            buttons : {
                                confirm : {
                                    className: 'btn btn-success'
                                }
                            }
                        });
                    } else {
                        swal("Deine Datei ist sicher!", {
                            buttons : {
                                confirm : {
                                    className: 'btn btn-success'
                                }
                            }
                        });
                    }
                });
            })

            $(document).delegate('#copySuccessAlert', 'click', function(e) {
                swal("Kopiert!", "Der Key ist jetzt in deiner Zwischenablage.", {
                    icon : "success",
                    buttons: {
                        confirm: {
                            className : 'btn btn-success'
                        }
                    },
                });
            })

            $(document).delegate('#downloadSuccessAlert', 'click', function(e) {
                swal("Download gestartet!", "Dein Download wurde gestartet.", {
                    icon : "success",
                    buttons: {
                        confirm: {
                            className : 'btn btn-success'
                        }
                    },
                });
            });

        };

        return {
            init: function() {
                initDemos();
            },
        };
    }();

    jQuery(document).ready(function() {
        SweetAlert2Demo.init();
    });
</script>
</body>
</html>
