<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="http://localhost/verany/www/terms/imprint.php">
                        Impressum
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://localhost/verany/www/terms/privacy.php">
                        Datenschutzerklärung
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright ml-auto">
            © <script>new Date().getFullYear()>2017&&document.write("2017-"+new Date().getFullYear());</script> Copyright Verany.net - Entwickelt von <a href="https://www.twitter.com/NicoVRNY" target="_blank">NicoVRNY</a>, <a href="https://twitter.com/RedHeadVRNY" target="_blank">Felix Unrein</a>, <a href="https://twitter.com/martiinhier" target="_blank">CuzImMartin</a> und <a href="https://www.themekita.com" target="_blank">ThemeKita</a>.
        </div>
    </div>
</footer>