<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Verany • Web Panel | Dashboard</title>
<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
<meta charset="utf-8">
<link rel="icon" href="/assets/img/logo.png" type="image/x-icon"/>

<script src="/assets/js/plugin/webfont/webfont.min.js"></script>
<script>
    WebFont.load({
        google: {"families":["Lato:300,400,700,900"]},
        custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['/assets/css/fonts.min.css']},
        active: function() {
            sessionStorage.fonts = true;
        }
    });
</script>

<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/css/atlantis.min.css">

<!-- Demo CSS -->
<link rel="stylesheet" href="/assets/css/demo.css">