<div class="main-header">
    <div class="logo-header" data-background-color="dark2">

        <a href="index.php" class="logo">
            <img src="/assets/img/logo.png" alt="navbar brand" class="navbar-brand" width="64" height="64">
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
        </button>
        <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
                <i class="icon-menu"></i>
            </button>
        </div>
    </div>

    <nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">

        <div class="container-fluid">
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                <li class="nav-item dropdown hidden-caret">
                    <a class="nav-link dropdown-toggle" href="#" id="messageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                    </a>
                    <ul class="dropdown-menu messages-notif-box animated fadeIn" aria-labelledby="messageDropdown">
                        <li>
                            <div class="dropdown-title d-flex justify-content-between align-items-center">
                                Nachrichten
                                <a href="#" class="small">Als gelesen markieren</a>
                            </div>
                        </li>
                        <li>
                            <div class="message-notif-scroll scrollbar-outer">
                                <div class="notif-center">
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="/assets//img/user/profile_images/userIcon-tylix_1.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">tylix</span>
                                            <span class="block">
														Schon aufm TeamSpeak?
													</span>
                                            <span class="time">vor 5 Minuten</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="/assets//img/user/profile_images/userIcon-SlashKick_1.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">SlashKick</span>
                                            <span class="block">
														Jo, passt!
													</span>
                                            <span class="time">vor 12 Minuten</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="/assets//img/user/profile_images/userIcon-RedHeadDerEchte_1.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">RedHeadDerEchte</span>
                                            <span class="block">
														Bereit fürs Meeting?
													</span>
                                            <span class="time">vor 13 Minuten</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="/assets//img/user/profile_images/userIcon-zzyfix_1.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">zzyfix</span>
                                            <span class="block">
														Hi, was geht?
													</span>
                                            <span class="time">vor 17 Minuten</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a class="see-all" href="javascript:void(0);">Alle Nachrichten<i class="fa fa-angle-right"></i> </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown hidden-caret">
                    <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="notification">4</span>
                    </a>
                    <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
                        <li>
                            <div class="dropdown-title">Du hast 4 Benachrichtigungen</div>
                        </li>
                        <li>
                            <div class="notif-scroll scrollbar-outer">
                                <div class="notif-center">
                                    <a href="#">
                                        <div class="notif-icon notif-primary"> <i class="fas fa-book"></i> </div>
                                        <div class="notif-content">
													<span class="block">
														Neues Update verfügbar
													</span>
                                            <span class="time">vor 5 Minuten</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-icon notif-primary"> <i class="fa fa-comment"></i> </div>
                                        <div class="notif-content">
													<span class="block">
														Neues Teamdokument
													</span>
                                            <span class="time">vor 12 Minuten</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="/assets//img/user/profile_images/userIcon-RedHeadDerEchte_1.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
													<span class="block">
														RedHeadDerEchte folgt dir jetzt.
													</span>
                                            <span class="time">vor 12 Minuten</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-icon notif-primary"> <i class="fas fa-tasks"></i> </div>
                                        <div class="notif-content">
													<span class="block">
														Neue Aufgabe für dich
													</span>
                                            <span class="time">vor 17 Minuten</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a class="see-all" href="javascript:void(0);">Alle Benachrichtigungen<i class="fa fa-angle-right"></i> </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown hidden-caret">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="avatar-sm">
                            <img src="https://mc-heads.net/avatar/<?php echo $_SESSION['profile']['uuid'];?>/164" alt="..." class="avatar-img rounded-circle">
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                        <div class="dropdown-user-scroll scrollbar-outer">
                            <li>
                                <div class="user-box">
                                    <div class="avatar-lg"><img src="https://mc-heads.net/avatar/<?php echo $_SESSION['profile']['uuid'];?>/164" alt="image profile" class="avatar-img rounded"></div>
                                    <div class="u-text">
                                        <h4><?php echo $_SESSION['profile']['username'];?></h4>
                                        <p class="text-muted"><?php echo $_SESSION['profile']['email'];?></p><a href="profile.php" class="btn btn-xs btn-primary btn-sm">Profil ansehen</a>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="http://localhost/verany/www/profile">Mein Profil</a>
                                <a class="dropdown-item" href="http://localhost/verany/www/profile/stats">Meine Statistiken</a>
                                <a class="dropdown-item" href="http://localhost/verany/www/support/overview">Support</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="http://localhost/verany/www/profile/settings">Einstellungen</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/logout">Abmelden</a>
                            </li>
                        </div>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <!-- End Navbar -->
</div>