<script src="/assets//js/core/jquery.3.2.1.min.js"></script>
<script src="/assets//js/core/popper.min.js"></script>
<script src="/assets//js/core/bootstrap.min.js"></script>

<script src="/assets//js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="/assets//js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>

<script src="/assets//js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

<script src="/assets//js/plugin/chart.js/chart.min.js"></script>

<script src="/assets//js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

<script src="/assets//js/plugin/chart-circle/circles.min.js"></script>

<script src="/assets//js/plugin/datatables/datatables.min.js"></script>

<script src="/assets//js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

<script src="/assets//js/plugin/jqvmap/jquery.vmap.min.js"></script>
<script src="/assets//js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>

<script src="/assets//js/plugin/sweetalert/sweetalert.min.js"></script>

<script src="/assets//js/atlantis.min.js"></script>

<script src="/assets//js/setting-demo.js"></script>
<script src="/assets//js/demo.js"></script>