<div class="sidebar sidebar-style-2" data-background-color="dark2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <ul class="nav nav-primary">
                <li class="nav-item active">
                    <a href="./">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                    <h4 class="text-section">Administration</h4>
                </li>
                <li class="nav-item">
                    <a href="/admin/config">
                        <i class="fas fa-cogs"></i>
                        <p>Konfiguration</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/admin/messages">
                        <i class="fas fa-edit"></i>
                        <p>Nachrichten</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#team">
                        <i class="fas fa-users"></i>
                        <p>Team</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="team">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="/admin/team/applications">
                                    <span class="sub-item">Bewerbungen</span>
                                </a>
                            </li>
                            <li>
                                <a href="/admin/team/assignment">
                                    <span class="sub-item">Zuweisung</span>
                                </a>
                            </li>
                            <li>
                                <a href="/admin/team/permissions">
                                    <span class="sub-item">Berechtigungen</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                    <h4 class="text-section">Team</h4>
                </li>
                <li class="nav-item">
                    <a href="/team/overview">
                        <i class="fas fa-clipboard"></i>
                        <p>Auflistung</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/team/tasks">
                        <i class="fas fa-tasks"></i>
                        <p>Aufgaben</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/team/documents">
                        <i class="fas fa-file-alt"></i>
                        <p>Dokumente</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/team/faq">
                        <i class="fas fa-question-circle"></i>
                        <p>FAQ</p>
                    </a>
                </li>
                <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                    <h4 class="text-section">Marketing</h4>
                </li>
                <li class="nav-item">
                    <a href="/marketing/overview">
                        <i class="fas fa-book-open"></i>
                        <p>Overview</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/marketing/partner">
                        <i class="far fa-star"></i>
                        <p>Partner</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/marketing/statistics">
                        <i class="fas fa-chart-bar"></i>
                        <p>Statistiken</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/marketing/giveaways">
                        <i class="fas fa-trophy"></i>
                        <p>Giveaways</p>
                    </a>
                </li>
                <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                    <h4 class="text-section">Konzeption</h4>
                </li>
                <li class="nav-item">
                    <a href="/conception/concepts">
                        <i class="far fa-folder"></i>
                        <p>Konzepte</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/conception/wishes">
                        <i class="fas fa-share"></i>
                        <p>Wünsche</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#maps">
                        <i class="fas fa-map"></i>
                        <p>Maps</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="maps">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="/conception/maps/overview">
                                    <span class="sub-item">Übersicht</span>
                                </a>
                            </li>
                            <li>
                                <a href="/conception/maps/submissions">
                                    <span class="sub-item">Einsendungen</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                    <h4 class="text-section">Moderation</h4>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#reports">
                        <i class="fas fa-envelope"></i>
                        <p>Meldungen</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="reports">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="/moderation/reports/game-behaviour">
                                    <span class="sub-item">Spielverhalten</span>
                                </a>
                            </li>
                            <li>
                                <a href="/moderation/reports/chat-behaviour">
                                    <span class="sub-item">Chatverhalten</span>
                                </a>
                            </li>
                            <li>
                                <a href="/moderation/reports/account-reports">
                                    <span class="sub-item">Account Report</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#unban">
                        <i class="fas fa-feather-alt"></i>
                        <p>Entbannungsanträge</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="unban">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="/moderation/unban/minecraft">
                                    <span class="sub-item">Minecraft</span>
                                </a>
                            </li>
                            <li>
                                <a href="/moderation/unban/teamspeak">
                                    <span class="sub-item">TeamSpeak</span>
                                </a>
                            </li>
                            <li>
                                <a href="/moderation/unban/discord">
                                    <span class="sub-item">Discord</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#check">
                        <i class="fas fa-arrows-alt-h"></i>
                        <p>Prüfen</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="check">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="/moderation/check/messages">
                                    <span class="sub-item">Nachrichten</span>
                                </a>
                            </li>
                            <li>
                                <a href="/moderation/check/hacking">
                                    <span class="sub-item">Hacking</span>
                                </a>
                            </li>
                            <li>
                                <a href="/moderation/check/names">
                                    <span class="sub-item">Namen</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                    <h4 class="text-section">Entwicklung</h4>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#docs">
                        <i class="fab fa-creative-commons-share"></i>
                        <p>Dokumentationen</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="docs">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="https://github.com/verany-network/client-development/tree/main#readme">
                                    <span class="sub-item">Verany Client</span>
                                </a>
                            </li>
                            <li>
                                <a href="/development/documentation/spigot">
                                    <span class="sub-item">Core</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#repo">
                        <i class="fab fa-github"></i>
                        <p>Version Control</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="repo">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="https://github.com/verany-network">
                                    <span class="sub-item">GitHub</span>
                                </a>
                            </li>
                            <li>
                                <a href="https://gitlab.com/verany">
                                    <span class="sub-item">GitLab</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#forms">
                        <i class="fas fa-server"></i>
                        <p>Server</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="forms">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="/development/server/overview">
                                    <span class="sub-item">Übersicht</span>
                                </a>
                            </li>
                            <li>
                                <a href="/development/server/servers">
                                    <span class="sub-item">Deine Server</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- End Sidebar -->