<!DOCTYPE html>
<html lang="de">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Verany • Web Panel | Anmelden</title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <meta charset="utf-8">
    <link rel="icon" href="/assets//img/logo.png" type="image/x-icon"/>

    <script src="/assets//js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: {"families":["Lato:300,400,700,900"]},
            custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['/assets//css/fonts.min.css']},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>
    <link rel="stylesheet" href="/assets//css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets//css/atlantis.min.css">
    <link rel="stylesheet" href="/assets//css/demo.css">
</head>
<body data-background-color="dark">
<div class="wrapper">
    <div class="main-header">
        <div class="logo-header" data-background-color="dark2">

            <a href="/" class="logo">
                <img src="/assets//img/favicon.png" alt="navbar brand" class="navbar-brand" width="32" height="32">
            </a>
        </div>

        <nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">

            <div class="container-fluid">
                <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                    <li class="nav-item dropdown hidden-caret">
                        <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                            <div class="avatar-sm">
                                <img src="/assets/img/question-icon.png" alt="..." class="avatar-img rounded-circle">
                            </div>
                        </a>
                        <ul class="dropdown-menu dropdown-user animated fadeIn">
                            <div class="dropdown-user-scroll scrollbar-outer">
                                <li>
                                    <div class="user-box">
                                        <div class="avatar-lg"><img src="/assets/img/question-icon.png" alt="image profile" class="avatar-img rounded"></div>
                                        <div class="u-text">
                                            <h4>Besucher</h4>
                                            <p class="text-muted">Unbekannter Besucher</p><a href="http://localhost/verany/www/profile/register.php" class="btn btn-xs btn-primary btn-sm">Registrieren</a>
                                        </div>
                                    </div>
                                </li>
                            </div>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- End Navbar -->
    </div>

    <!-- Sidebar -->
    <div class="sidebar sidebar-style-2" data-background-color="dark2">
        <div class="sidebar-wrapper scrollbar scrollbar-inner">
            <div class="sidebar-content">
                <ul class="nav nav-primary">
                    <li class="nav-item">
                        <a href="http://localhost/verany/www/">
                            <i class="fas fa-home"></i>
                            <p>Startseite</p>
                        </a>
                    </li>

                    <li class="nav-section">
							<span class="sidebar-mini-icon">
								<i class="fa fa-ellipsis-h"></i>
							</span>
                        <h4 class="text-section">Profil</h4>
                    </li>

                    <li class="nav-item">
                        <a href="http://localhost/verany/www/profile/register.php">
                            <i class="fas fa-feather-alt"></i>
                            <p>Registrieren</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="https://verany.net">
                            <i class="fas fa-sign-in-alt"></i>
                            <p>Anmelden</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- End Sidebar -->

    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <h4 class="page-title">Anmelden</h4>
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="/">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Profile</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Login</a>
                        </li>
                    </ul>
                </div>

                <div class="page-category">
                    <div class="row row-card-no-pd">
                        <div class="col-md-12">
                            <div class="card">

                                <form method="post">
                                    <div class="card-header">
                                        <div class="card-head-row">
                                            <h4 class="card-title">Anmeldung</h4>
                                            <div class="card-tools">
                                                <button class="btn btn-icon btn-link btn-primary btn-xs"><span class="fas fa-feather-alt"></span></button>
                                            </div>
                                        </div>
                                        <p class="card-category">
                                            Trage hier die in der <a href="http://localhost/verany/www/profile/register.php">Registrierung</a> eingetragenen Daten ein.</p>
                                    </div>
                                    <div class="card-body">
                                        <div class="input-icon">
                                                <span class="input-icon-addon">
                                                    <i class="fa fa-user"></i>
                                                </span>
                                            <input type="text" class="form-control" placeholder="Minecraft Username" name="username" required>
                                        </div>
                                        <br>
                                        <div class="input-icon">
                                                <span class="input-icon-addon">
                                                    <i class="fas fa-lock-open"></i>
                                                </span>
                                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                                        </div>
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input class="form-check-input" type="checkbox" name="rememberme">
                                                <span class="form-check-sign">In den nächsten 30 Tagen angemeldet bleiben</span>
                                            </label>
                                        </div>
                                        <button class="btn btn-primary" name="submit">Anmelden</button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="http://localhost/verany/www/terms/imprint.php">
                                Impressum
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="http://localhost/verany/www/terms/privacy.php">
                                Datenschutzerklärung
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright ml-auto">
                    © <script>new Date().getFullYear()>2017&&document.write("2017-"+new Date().getFullYear());</script> Copyright Verany.net - Entwickelt von <a href="https://www.twitter.com/NicoVRNY">NicoVRNY</a> und <a href="https://www.themekita.com">ThemeKita</a>.
                </div>
            </div>
        </footer>
    </div>

</div>

<!--   Core JS Files   -->
<script src="/assets//js/core/jquery.3.2.1.min.js"></script>
<script src="/assets//js/core/popper.min.js"></script>
<script src="/assets//js/core/bootstrap.min.js"></script>
<!-- jQuery UI -->
<script src="/assets//js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="/assets//js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<!-- jQuery Scrollbar -->
<script src="/assets//js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<!-- Chart JS -->
<script src="/assets//js/plugin/chart.js/chart.min.js"></script>
<!-- jQuery Sparkline -->
<script src="/assets//js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
<!-- Chart Circle -->
<script src="/assets//js/plugin/chart-circle/circles.min.js"></script>
<!-- Datatables -->
<script src="/assets//js/plugin/datatables/datatables.min.js"></script>
<!-- Bootstrap Notify -->
<script src="/assets//js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
<!-- jQuery Vector Maps -->
<script src="/assets//js/plugin/jqvmap/jquery.vmap.min.js"></script>
<script src="/assets//js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
<!-- Sweet Alert -->
<script src="/assets//js/plugin/sweetalert/sweetalert.min.js"></script>
<!-- Atlantis JS -->
<script src="/assets//js/atlantis.min.js"></script>

</body>
</html>