<!DOCTYPE html>
<html lang="de">
<head>
    <?php include(ROOT_PATH."/app/views/forms/html.phtml")?>
</head>
<body class="page-body">
<!-- navbar -->
<?php include(ROOT_PATH."/app/views/forms/nav.phtml")?>
<!-- /.navbar -->

<!-- header -->
<header class="header">
    <div id="carousel_main" class="carousel carousel-header slide carousel-fade fl-scn" data-ride="carousel">
        <!-- Indicators -->
        <div class="po_carousel__wrapper">
            <ol class="list-unstyled carousel-indicators def po_carousel-indicators">
                <li data-target="#carousel_main" data-slide-to="0" class="active"></li>
                <li data-target="#carousel_main" data-slide-to="1" class=""></li>
                <li data-target="#carousel_main" data-slide-to="2" class=""></li>
            </ol>
        </div>
        <!-- Carousel items -->
        <div class="carousel-inner a-cont">
            <!-- carousel-item -->
            <div class="carousel-item active">
                <div class="h-fullscreen__page bs-c br-n ow-h" style="background-image: url(/assets/img/content/carousel/home-slide_01.png);">
                    <div class="w-100 d-flex jc-c overlay">
                        <!-- sm-overlay -->
                        <div class="overlay bg-light_A-20 d-lg-none"></div>
                        <div class="overlay bg-dark_A-50 d-lg-none"></div>
                        <!-- lg-overlay -->
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape__light light_A-2" data-carousel-animation="fade"></div>
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape ad-200ms" data-carousel-animation="fade"></div>
                    </div>
                    <div class="d-flex align-items-center h-100">
                        <div class="container">
                            <div class="row align-items-center h-100">
                                <div class="col-12 mr-auto ml-lg-0 col-lg-5">

                                    <div class="main_carousel__content ad-900ms fadeIn text-light px-8 px-md-6 mx-lg-4 mx-xl-0">

                                        <h2 class="carousel__heading text-light fadeInDown ad-500ms">TeamSpeak Release!</h2>
                                        <p class="carousel__text lead-1 mb-6 fadeInDown ad-600ms">Come to our TeamSpeak to talk with your friends or to meet new friends!</p>
                                        <div class="d-flex fadeInLeft ad-900ms">
                                            <a class="disabled btn btn-lg bg-dark_A-50 o-1 text-light br-round-0tr br-round-0br parallelogram un_text mb-0"><span class="carousel__discount td-lt text-light"><i class="fab fa-teamspeak"></i></span></a>
                                            <a href="ts3server://verany.net" class="btn btn-lg btn-light parallelogram br-round-0tl br-round-0bl un_text mb-0"><span class="d-block">Join</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.carousel-item -->

            <!-- carousel-item -->
            <div class="carousel-item">
                <div class="h-fullscreen__page bs-c br-n ow-h" style="background-image: url(/assets/img/content/carousel/home-slide_02.png);">
                    <div class="w-100 d-flex jc-c overlay">
                        <!-- sm-overlay -->
                        <div class="overlay bg-light_A-20 d-lg-none"></div>
                        <div class="overlay bg-dark_A-50 d-lg-none"></div>
                        <!-- lg-overlay -->
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape__light light_A-2" data-carousel-animation="fade"></div>
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape ad-200ms" data-carousel-animation="fade"></div>
                    </div>
                    <div class="d-flex align-items-center h-100">
                        <div class="container">
                            <div class="row align-items-center h-100">
                                <div class="col-12 mr-auto ml-lg-0 col-lg-5">
                                    <div class="main_carousel__content ad-900ms fadeIn text-light px-8 px-md-6 mx-lg-4 mx-xl-0">

                                        <h2 class="carousel__heading text-light fadeInDown ad-500ms">Discord release!</h2>
                                        <p class="carousel__text lead-1 mb-6 fadeInDown ad-600ms">Enter our Discord to participate in giveaways or to get in touch with our team.</p>
                                        <div class="d-flex fadeInLeft ad-900ms">
                                            <a class="disabled btn btn-lg bg-dark_A-50 o-1 text-light br-round-0tr br-round-0br parallelogram un_text mb-0"><span class="carousel__discount td-lt text-light"><i class="fab fa-discord"></i></span></a>
                                            <a href="https://discord.gg/SJ5tfxC" class="btn btn-lg btn-light parallelogram br-round-0tl br-round-0bl un_text mb-0"><span class="d-block">Join</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.carousel-item -->

            <!-- carousel-item -->
            <div class="carousel-item">
                <div class="h-fullscreen__page bs-c br-n ow-h" style="background-image: url(/assets/img/content/carousel/home-slide_03.png);">
                    <div class="w-100 d-flex jc-c overlay">
                        <!-- sm-overlay -->
                        <div class="overlay bg-light_A-20 d-lg-none"></div>
                        <div class="overlay bg-dark_A-50 d-lg-none"></div>
                        <!-- lg-overlay -->
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape__light light_A-2" data-carousel-animation="fade"></div>
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape ad-200ms" data-carousel-animation="fade"></div>
                    </div>
                    <div class="d-flex align-items-center h-100">
                        <div class="container">
                            <div class="row align-items-center h-100">
                                <div class="col-12 mr-auto ml-lg-0 col-lg-5">
                                    <div class="main_carousel__content ad-900ms fadeIn text-light px-8 px-md-6 mx-lg-4 mx-xl-0">

                                        <h2 class="carousel__heading text-light fadeInDown ad-500ms">Follow us on Twitter</h2>
                                        <p class="carousel__text lead-1 mb-6 fadeInDown ad-600ms"></p>
                                        <div class="d-flex fadeInLeft ad-900ms">
                                            <a class="disabled btn btn-lg bg-dark_A-50 o-1 text-light br-round-0tr br-round-0br parallelogram un_text mb-0"><span class="carousel__discount td-lt text-light"><i class="fab fa-twitter"></i></span></a>
                                            <a href="http://twitter.com/intent/user?screen_name=VeranyNET" class="btn btn-lg btn-light parallelogram br-round-0tl br-round-0bl un_text mb-0"><span class="d-block">Follow</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.carousel-item -->

        </div>
        <!-- Carousel nav -->
        <div class="carousel-control-prev a-out-t"><a class="text-light" href="#carousel_main" data-slide="prev"><span class="icon-cl-prev text-shadow pe-7s-angle-left"></span></a></div>
        <div class="carousel-control-next a-out-t"><a class="text-light" href="#carousel_main" data-slide="next"><span class="icon-cl-next text-shadow pe-7s-angle-right"></span></a></div>
    </div>
</header>
<!-- /.header -->

<!-- main content -->
<main class="main-content">

    <!-- content area -->
    <section class="content-section owl-carousel-spotlight carousel-spotlight ig-carousel text-light">
        <div class="container">
            <div class="position-relative">
                <!-- nav tabs -->
                <ul class="spotlight-tabs spotlight-tabs-dark nav nav-tabs border-0 mb-5 position-relative flex-nowrap" id="most_popular_products-carousel" role="tablist">
                    <li class="nav-item text-fnwp pg-none relative">
                        <a class="nav-link active" id="mp-01-tab" data-toggle="tab" href="#mp-01-c" role="tab" aria-controls="mp-01-c" aria-selected="true">Our Games</a>
                    </li>
                    <li class="nav-item text-fnwp relative">
                        <a class="nav-link" id="mp-02-tab" data-toggle="tab" href="#mp-02-c" role="tab" aria-controls="mp-02-c" aria-selected="false">Popular Store Items</a>
                    </li>
                </ul>
                <!-- /.nav tabs -->
                <!-- tab panes -->
                <div id="color_sel_Carousel-content" class="tab-content fl-scn relative w-100">

                    <!-- tab item -->
                    <div class="tab-pane fade show active" id="mp-01-c" role="tabpanel" aria-labelledby="mp-01-tab">
                        <div class="owl-carousel gs-carousel" data-carousel-margin="30" data-carousel-nav="true" data-carousel-navText="<span class='icon-cl-next pe-7s-angle-left'></span>, <span class='icon-cl-next pe-7s-angle-right'></span>">
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/games/flagwars.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">FLAGWARS</a></h5>
                                                <div class="relative small-1">
                                                    <span>If you enjoy games like BedWars and Tower Defense, you will love FlagWars.</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/games/snowwars.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">SNOWWARS</a></h5>
                                                <div class="relative small-1">
                                                    <span>A snowball fight with up to 12 players: alone or in a team, fun is guaranteed.</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/games/duels.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">DUELS</a></h5>
                                                <div class="relative small-1">
                                                    <span>From classic kit fights to sumo, oneline and SkyWars to personalized tournaments, everyone will find their luck in duels.</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/games/survival.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">SURVIVAL</a></h5>
                                                <div class="relative small-1">
                                                    <span>Your own shop, a huge mall, an infinitely large beautiful map and your own minions.</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/games/rpg.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">RPG</a></h5>
                                                <div class="relative small-1">
                                                    <span>New quests every day, a breathtaking, living map with a comprehensive infrastructure.</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                        </div>
                    </div>
                    <!-- /.tab item -->

                    <!-- tab item -->
                    <div class="tab-pane fade" id="mp-02-c" role="tabpanel" aria-labelledby="mp-02-tab">
                        <div class="owl-carousel gs-carousel" data-carousel-margin="30" data-carousel-nav="true" data-carousel-navText="<span class='icon-cl-next pe-7s-angle-left'></span>, <span class='icon-cl-next pe-7s-angle-right'></span>">
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/store/rank-vip_lifetime.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">BUY</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">VIP (LIFETIME)</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">40,00 €</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/store/rank-vipplus_1year.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">VIP+ (12 Months)</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">50,00 €</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/store/rank-vip_1month.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">VIP (30 Days)</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">10,00 €</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/store/rank-vip_3months.png" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">VIP (3 Months)</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">25,00 €</span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                        </div>
                    </div>
                    <!-- /.tab item -->

                    <!-- tab item -->
                    <div class="tab-pane fade" id="mp-03-c" role="tabpanel" aria-labelledby="mp-03-tab">
                        <div class="owl-carousel gs-carousel" data-carousel-margin="30" data-carousel-nav="true" data-carousel-navText="<span class='icon-cl-next pe-7s-angle-left'></span>, <span class='icon-cl-next pe-7s-angle-right'></span>">
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/cg_01.jpg" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">Donec dignissim ...</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">€1.87</span>
                                                    <span class="owl_item_genre">
                                PVP
                              </span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/cg_01.jpg" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">Donec dignissim ...</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">€1.87</span>
                                                    <span class="owl_item_genre">
                                PVP
                              </span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/cg_01.jpg" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">Donec dignissim ...</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">€1.87</span>
                                                    <span class="owl_item_genre">
                                PVP
                              </span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/cg_01.jpg" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">Donec dignissim ...</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">€1.87</span>
                                                    <span class="owl_item_genre">
                                PVP
                              </span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                            <!-- item -->
                            <div class="item">
                                <div class="item-cont">
                                    <figure class="owl_item_review">
                                        <div>
                                            <div class="position-relative overflow-hidden">
                                                <img class="m-0-auto" src="/assets/img/content/cont/cg_01.jpg" alt="Games Store">
                                                <div class="review_h text-light">
                                                    <a href="#">
                                                        <i class="item_icon_cart fas fa-shopping-cart"></i>
                                                        <span class="item_atc_text">MORE</span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div>
                                                <h5 class="owl_item_title text-lt"><a href="">Donec dignissim ...</a></h5>
                                                <div class="relative small-1">
                                                    <span class="owl_item_price">€1.87</span>
                                                    <span class="owl_item_genre">
                                PVP
                              </span>
                                                </div>
                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                            <!-- /.item -->
                        </div>
                    </div>
                    <!-- /.tab item -->

                </div>
                <!-- /.tab panes -->
            </div>
        </div>
    </section>
    <!-- /.content area -->

    <!-- content area -->
    <section class="content-section text-light" style="background: linear-gradient(to bottom, #111931 0%, #0f131e 100%);">
        <div class="container">
            <header class="header text-left">
                <h2 class="mb-6">Latest News</h2>
            </header>
            <div class="row">
                <!-- post -->
                <div class="col-12 mb-8">
                    <div class="row">
                        <div class="col-lg-4 mb-6 mb-lg-0">
                            <div class="card">
                                <div class="img__news_wrapper"><img src="/assets/img/content/news/discord.jpg" alt="News"></div>
                                <div class="badges badges-left badges-bottom text-white">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <h4 class="text-uppercase mb-3">Discord release</h4>
                            <div class="mb-3 small text-info">
                                <span><i class="fas fa-tags"></i> Announcements</span> <span class="mx-1">-</span> <span>6th Decemer 2020</span>
                            </div>
                            <p>Join our Discord to get the newest informations about Verany and to meet new people and make new friends.</p>
                            <a href="https://twitter.com/VeranyNET/status/1267886199043055617" class="btn btn-outline-light">Read</a>
                        </div>
                    </div>
                </div>
                <!-- /.post -->

                <!-- post -->
                <div class="col-12 mb-8">
                    <div class="row">
                        <div class="col-lg-4 mb-6 mb-lg-0">
                            <div class="card">
                                <div class="img__news_wrapper"><img src="/assets/img/content/news/ts.jpg" alt="News"></div>
                                <div class="badges badges-left badges-bottom text-white">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <h4 class="text-uppercase mb-3">TeamSpeak release</h4>
                            <div class="mb-3 small text-info">
                                <span><i class="fas fa-tags"></i> Announcements</span> <span class="mx-1">-</span> <span>5th Decemer 2020</span>
                            </div>
                            <p>Join our TeamSpeak to get support by our team and to talk with your friends or even find new people to talk with.</p>
                            <a href="https://twitter.com/VeranyNET/status/1270060525787832321" class="btn btn-outline-light">Read</a>
                        </div>
                    </div>
                </div>
                <!-- /.post -->

                <!-- post -->
                <div class="col-12">
                    <div class="row">
                        <div class="col-lg-4 mb-6 mb-lg-0">
                            <div class="card">
                                <div class="img__news_wrapper"><img src="/assets/img/content/news/wereback.jpg" alt="News"></div>
                                <div class="badges badges-left badges-bottom text-white">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <h4 class="text-uppercase mb-3">We are back!</h4>
                            <div class="mb-3 small text-info">
                                <span><i class="fas fa-tags"></i> Announcements</span> <span class="mx-1">-</span> <span>4th Decemer 2020</span>
                            </div>
                            <p>Now it's official! We are now back and try to merge with Veranity to present you the best version of our networks.</p>
                            <a href="https://twitter.com/VeranyNET/status/1267523809587810304" class="btn btn-outline-light">Read</a>
                        </div>
                    </div>
                </div>
                <!-- /.post -->
            </div>
        </div>
    </section>
    <!-- /.content area -->

    <!-- content area -->
    <section class="section gs_features">
        <div class="row no-gutters">
            <div class="col-xl-6 py-6 px-4 px-sm-8 6 px-md-9 " data-overlay="7">
                <div class="row align-items-center h-100">
                    <div class="col-sm-6 col-md-4 order-md-2 mb-6 mb-md-0">
                        <figure class="position-relative my-0">
                            <div style="background-image: url('/assets/img/content/cont/partnerLaby.png'); width: 280px;" class="main-fb-product bp-c br-n">
                            </div>
                        </figure>
                    </div>
                    <div class="col-md-8 order-md-1 text-light text-md-right">
                        <h2 class="mb-4">LabyMod</h2>
                        <p class="mb-7">Thanks to our closer collaboration with ReyFM, we are able to offer a customized gaming experience for everyone.</p>
                    </div>
                </div>
            </div>

            <div class="col-xl-6 py-6 px-4 px-sm-8 py-md-6 px-md-9 " data-overlay="7">
                <div class="row align-items-center h-100">
                    <div class="col-sm-6 col-md-4 order-md-2 mb-6 mb-md-0">
                        <figure class="position-relative my-0">
                            <div style="background-image: url('/assets/img/content/cont/partnerReyFM.png'); width: 280px;" class="main-fb-product bp-c br-n">
                            </div>
                        </figure>
                    </div>
                    <div class="col-md-8 order-md-1 text-light text-md-right">
                        <h2 class="mb-4">ReyFM</h2>
                        <p class="mb-7">Thanks to our closer collaboration with ReyFM, we are able to offer you a high-performance music experience around the clock.</p>
                    </div>
                </div>
            </div>

            <div class="row no-gutters">
    </section>
</main>


<!-- footer -->
<?php include(ROOT_PATH."/app/views/forms/footer.phtml")?>
<!-- /.footer -->

<!-- sign in -->
<div style="overflox-y: hidden" class="modal fade" id="userLogin" tabindex="-1" role="dialog" aria-labelledby="userLoginTitle" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
        <div class="modal-content bg-dark text-light">
            <div class="modal-header border-secondary">
                <h5 class="modal-title" id="userLoginTitle">Sign in</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="input-transparent" action="" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control border-secondary" name="log_username" autocomplete="off" placeholder="Minecraft Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control border-secondary" name="log_password" autocomplete="off" placeholder="Password">
                    </div>
                    <div class="form-group d-flex justify-content-between">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" checked="" id="rememberMeCheck">
                            <label class="custom-control-label" for="rememberMeCheck">Remember me</label>
                        </div>
                        <a class="small-3" href="#">Forgot password?</a>
                    </div>
                    <div class="form-group mt-6">
                        <button class="btn btn-block btn-light" type="submit">Sign in</button>
                    </div>
                </form>
                <span class="small">Don't have an account? <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#userSignUp">Create an account</a></span>
            </div>
        </div>
    </div>
</div>
<!-- /.sign in -->
<!-- sign up -->
<div class="modal fade" id="userSignUp" tabindex="-1" role="dialog" aria-labelledby="userSignUpTitle" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
        <div class="modal-content bg-dark text-light">
            <div class="modal-header border-secondary">
                <h5 class="modal-title" id="userSignUp">Sign up</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post" class="input-transparent">
                    <div class="form-group">
                        <input type="email" class="form-control border-secondary" name="reg_email" autocomplete="off" placeholder="E-Mail Adresse" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control border-secondary" name="reg_password" autocomplete="off" placeholder="Password" required>
                    </div>
                    <div class="form-group mb-0">
                        <input type="text" class="form-control border-secondary" name="reg_key" autocomplete="off" placeholder="Enter Your Code" required>
                        <div class="input-group-append ml-3"></div>
                    </div>
                    <div class="form-group mt-6">
                        <button class="btn btn-block btn-light" type="submit">Sign up</button>
                    </div>
                </form>
                <span class="small">Already have an account? <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#userSignIn" >Log in</a></span>
            </div>
        </div>
    </div>
</div>
<?php if(false) {
?>
<!-- offcanvas-cart -->
<div id="offcanvas-cart" class="offcanvas-cart offcanvas text-light h-100 r-0 l-auto d-flex flex-column" data-animation="slideRight">
    <div>
        <button type="button" data-toggle="offcanvas-close" class="close float-right ml-4 text-light o-1 fw-100" data-dismiss="offcanvas" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <hr class="border-light o-20 mt-8 mb-4">
    </div>
    <div class="offcanvas-cart-body flex-1">
        <div class="offcanvas-cart-list row align-items-center no-gutters">
            <div class="ocs-cart-item col-12">
                <div class="row align-items-center no-gutters">
                    <div class="col-3 item_img d-none d-sm-block">
                        <a href="store-product.html"><img class="img bl-3 text-primary" src="./../assets/img/content/cont/cg-h_01.jpg" alt="Product"></a>
                    </div>
                    <div class="col-7 flex-1 flex-grow pl-0 pl-sm-4 pr-4">
                        <a href="store-product.html"><span class="d-block item_title text-lt ls-1 lh-1 small-1 fw-600 text-uppercase mb-2">VIP (Lifetime)</span></a>
                        <div class="position-relative lh-1">
                            <div class="number-input">
                                <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" ><i class="ti-minus"></i></button>
                                <input class="quantity" min="0" name="quantity" value="1" type="number">
                                <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()"><i class="ti-plus"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="row align-items-center h-100 no-gutters">
                            <div class="ml-auto text-center">
                                <a href="#"><i class="far fa-trash-alt"></i></a><br>
                                <span class="fw-500 text-warning">30,00 €</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ocs-cart-item col-12">
                <div class="row align-items-center no-gutters">
                    <div class="col-3 item_img d-none d-sm-block">
                        <a href="store-product.html"><img class="img bl-3 text-primary" src="./../assets/img/content/cont/cg-h_01.jpg" alt="Product"></a>
                    </div>
                    <div class="col-7 flex-1 flex-grow pl-0 pl-sm-4 pr-4">
                        <a href="store-product.html"><span class="d-block item_title text-lt ls-1 lh-1 small-1 fw-600 text-uppercase mb-2">JoinMe Tokens</span></a>
                        <div class="position-relative lh-1">
                            <div class="number-input">
                                <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" ><i class="ti-minus"></i></button>
                                <input class="quantity" min="0" name="quantity" value="10" type="number">
                                <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()"><i class="ti-plus"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="row align-items-center h-100 no-gutters">
                            <div class="ml-auto text-center">
                                <a href="#"><i class="far fa-trash-alt"></i></a><br>
                                <span class="fw-500 text-warning">3,75 €</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <a href="checkout-order.html" class="btn btn-lg btn-block btn-outline-light">View cart</a>
    </div>
</div>
<!-- /.offcanvas-cart -->
<?php } ?>

<?php include(ROOT_PATH."/app/views/forms/script.phtml")?>

<?php
if($this->SignUp) { ?>
    <script>
        $( document ).ready(function() {
            $("#SignUp").trigger( "click" );
        });
    </script>
<?php }
if($this->SignIn) { ?>
    <script>
        $( document ).ready(function() {
            $("#SignIn").trigger( "click" );
        });
    </script>
<?php } ?>


</body>
</html>
