<!DOCTYPE html>
<html lang="de">
<head>
    <?php include(ROOT_PATH."/app/views/forms/html.ptml")?>
</head>
<body class="page-body">
<!-- navbar -->

<?php include(ROOT_PATH."/app/views/forms/nav.ptml")?>
<!-- /.navbar -->

<!-- header -->
<header class="header">
    <div id="carousel_main" class="carousel carousel-header slide carousel-fade fl-scn" data-ride="carousel">
        <!-- Indicators -->
        <div class="po_carousel__wrapper">
            <ol class="list-unstyled carousel-indicators def po_carousel-indicators">
                <li data-target="#carousel_main" data-slide-to="0" class="active"></li>
                <li data-target="#carousel_main" data-slide-to="1" class=""></li>
                <li data-target="#carousel_main" data-slide-to="2" class=""></li>
            </ol>
        </div>
        <!-- Carousel items -->
        <div class="carousel-inner a-cont">
            <!-- carousel-item -->
            <div class="carousel-item active">
                <div class="h-fullscreen__page bs-c br-n ow-h" style="background-image: url(/assets/img/content/carousel/home-slide_01.png);">
                    <div class="w-100 d-flex jc-c overlay">
                        <!-- sm-overlay -->
                        <div class="overlay bg-light_A-20 d-lg-none"></div>
                        <div class="overlay bg-dark_A-50 d-lg-none"></div>
                        <!-- lg-overlay -->
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape__light light_A-2" data-carousel-animation="fade"></div>
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape ad-200ms" data-carousel-animation="fade"></div>
                    </div>
                    <div class="d-flex align-items-center h-100">
                        <div class="container">
                            <div class="row align-items-center h-100">
                                <div class="col-12 mr-auto ml-lg-0 col-lg-5">

                                    <div class="main_carousel__content ad-900ms fadeIn text-light px-8 px-md-6 mx-lg-4 mx-xl-0">

                                        <h2 class="carousel__heading text-light fadeInDown ad-500ms">TeamSpeak Release!</h2>
                                        <p class="carousel__text lead-1 mb-6 fadeInDown ad-600ms">Come to our TeamSpeak to talk with your friends or to meet new friends!</p>
                                        <div class="d-flex fadeInLeft ad-900ms">
                                            <a class="disabled btn btn-lg bg-dark_A-50 o-1 text-light br-round-0tr br-round-0br parallelogram un_text mb-0"><span class="carousel__discount td-lt text-light"><i class="fab fa-teamspeak"></i></span></a>
                                            <a href="ts3server://verany.net" class="btn btn-lg btn-light parallelogram br-round-0tl br-round-0bl un_text mb-0"><span class="d-block">Join</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.carousel-item -->

            <!-- carousel-item -->
            <div class="carousel-item">
                <div class="h-fullscreen__page bs-c br-n ow-h" style="background-image: url(/assets/img/content/carousel/home-slide_02.png);">
                    <div class="w-100 d-flex jc-c overlay">
                        <!-- sm-overlay -->
                        <div class="overlay bg-light_A-20 d-lg-none"></div>
                        <div class="overlay bg-dark_A-50 d-lg-none"></div>
                        <!-- lg-overlay -->
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape__light light_A-2" data-carousel-animation="fade"></div>
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape ad-200ms" data-carousel-animation="fade"></div>
                    </div>
                    <div class="d-flex align-items-center h-100">
                        <div class="container">
                            <div class="row align-items-center h-100">
                                <div class="col-12 mr-auto ml-lg-0 col-lg-5">
                                    <div class="main_carousel__content ad-900ms fadeIn text-light px-8 px-md-6 mx-lg-4 mx-xl-0">

                                        <h2 class="carousel__heading text-light fadeInDown ad-500ms">Discord release!</h2>
                                        <p class="carousel__text lead-1 mb-6 fadeInDown ad-600ms">Enter our Discord to participate in giveaways or to get in touch with our team.</p>
                                        <div class="d-flex fadeInLeft ad-900ms">
                                            <a class="disabled btn btn-lg bg-dark_A-50 o-1 text-light br-round-0tr br-round-0br parallelogram un_text mb-0"><span class="carousel__discount td-lt text-light"><i class="fab fa-discord"></i></span></a>
                                            <a href="https://discord.gg/SJ5tfxC" class="btn btn-lg btn-light parallelogram br-round-0tl br-round-0bl un_text mb-0"><span class="d-block">Join</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.carousel-item -->

            <!-- carousel-item -->
            <div class="carousel-item">
                <div class="h-fullscreen__page bs-c br-n ow-h" style="background-image: url(/assets/img/content/carousel/home-slide_03.png);">
                    <div class="w-100 d-flex jc-c overlay">
                        <!-- sm-overlay -->
                        <div class="overlay bg-light_A-20 d-lg-none"></div>
                        <div class="overlay bg-dark_A-50 d-lg-none"></div>
                        <!-- lg-overlay -->
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape__light light_A-2" data-carousel-animation="fade"></div>
                        <div class="d-none d-lg-block position-absolute triangle-bottomleft a-out carousel-shape ad-200ms" data-carousel-animation="fade"></div>
                    </div>
                    <div class="d-flex align-items-center h-100">
                        <div class="container">
                            <div class="row align-items-center h-100">
                                <div class="col-12 mr-auto ml-lg-0 col-lg-5">
                                    <div class="main_carousel__content ad-900ms fadeIn text-light px-8 px-md-6 mx-lg-4 mx-xl-0">

                                        <h2 class="carousel__heading text-light fadeInDown ad-500ms">Follow us on Twitter</h2>
                                        <p class="carousel__text lead-1 mb-6 fadeInDown ad-600ms"></p>
                                        <div class="d-flex fadeInLeft ad-900ms">
                                            <a class="disabled btn btn-lg bg-dark_A-50 o-1 text-light br-round-0tr br-round-0br parallelogram un_text mb-0"><span class="carousel__discount td-lt text-light"><i class="fab fa-twitter"></i></span></a>
                                            <a href="http://twitter.com/intent/user?screen_name=VeranyNET" class="btn btn-lg btn-light parallelogram br-round-0tl br-round-0bl un_text mb-0"><span class="d-block">Follow</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.carousel-item -->

        </div>
        <!-- Carousel nav -->
        <div class="carousel-control-prev a-out-t"><a class="text-light" href="#carousel_main" data-slide="prev"><span class="icon-cl-prev text-shadow pe-7s-angle-left"></span></a></div>
        <div class="carousel-control-next a-out-t"><a class="text-light" href="#carousel_main" data-slide="next"><span class="icon-cl-next text-shadow pe-7s-angle-right"></span></a></div>
    </div>
</header>
<!-- /.header -->

<!-- main content -->
<main class="main-content">

</main>
<!-- footer -->
<?php include(ROOT_PATH."/app/views/forms/footer.phtml")?>
<!-- /.footer -->
<?php include(ROOT_PATH."/app/views/forms/script.phtml")?>
</body>
</html>
